In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np
import pandas as pd

In [2]:
# Load the Iris dataset
iris = load_iris()

X = iris.data        # features
y = iris.target      # labels

print("Dataset Loaded Successfully!")
print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)

Dataset Loaded Successfully!
Feature Shape: (150, 4)
Target Shape: (150,)


In [3]:
# Splitting dataset (80% train, 20% test)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training Set Size:", X_train.shape)
print("Testing Set Size:", X_test.shape)

Training Set Size: (120, 4)
Testing Set Size: (30, 4)


In [4]:
# Using KNN classifier

knn = KNeighborsClassifier(n_neighbors=3)

# Train the model
knn.fit(X_train, y_train)

print("Model Training Completed!")

Model Training Completed!


In [5]:
# Predict on test data

y_pred = knn.predict(X_test)

print("Predictions Done!")
print("Predicted Values:", y_pred)

Predictions Done!
Predicted Values: [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [6]:
# Calculate Accuracy

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy of the Model:", accuracy)

Accuracy of the Model: 1.0


In [7]:
# Confusion Matrix

conf_matrix = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:\n")
print(conf_matrix)

Confusion Matrix:

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [8]:
# Precision, Recall, F1-score

report = classification_report(y_test, y_pred)

print("Classification Report:\n")
print(report)

Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

