In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

In [2]:
# Load the Iris dataset
iris = load_iris()

X = iris.data        # features
y = iris.target      # labels

print("Dataset Loaded Successfully!")
print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)

Dataset Loaded Successfully!
Feature Shape: (150, 4)
Target Shape: (150,)


In [3]:
# Split the data (80% training, 20% testing)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training Set Shapes:")
print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("\nTesting Set Shapes:")
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

Training Set Shapes:
X_train: (120, 4)
y_train: (120,)

Testing Set Shapes:
X_test: (30, 4)
y_test: (30,)


In [4]:
# Display first 5 rows of features and labels

print("Sample Feature Data (X):")
print(X[:5])

print("\nSample Target Data (y):")
print(y[:5])

Sample Feature Data (X):
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Sample Target Data (y):
[0 0 0 0 0]
